export const WALLET_MODE_NOTIFICATIONS = {
  ERROR_INVALID_AMOUNT: "Invalid Amount",
  BALANCE_TOO_LOW: "Available Balance Too Low",
  TRY_CUSTOM_FEE: "Retry, Switch RPC, or Use Custom Gwei",
  ADDED_RAILGUN_FEE: "Added 0.25% Railgun Fee",
  FUNDS_IN_TRANSIT: "Confirming on chain…",
  TX_CANCELLED: "Transaction Cancelled",
  ESTIMATION_CANCELLED: "Estimation Cancelled",
  ERROR_ESTIMATING_GAS: "Error Estimating Gas",
  ERROR_WITH_SENDING: "Problem Sending Transaction",
  ERROR_ENCRYPTION_BUS_ALREADY_WAITING: "Already waiting for the encryption bus key",
  ERROR_NO_ACTIVE_ENCRYPTION_BUS_LISTENERS: "No active encryption bus listeners to receive the key",
  ERROR_CANCELLED_ENCRYPTION_BUS: "Action Cancelled",
  ERROR_NOTES_ALREADY_SPENT: "Check Your Token Balance",
  TOKEN_APPROVAL_ERROR: "Failed Approving Tokens",
  ERROR_FINDING_BROADCASTER: "Problem Finding Broadcaster",
  FINDING_DEFAULT_BROADCASTER_FOR_TOKEN_ERROR: "Problem Finding Broadcaster",
  GENERAL_BROADCASTER_ERROR: "Try Another Broadcaster or Provider",
  POPULATION_ERROR: "Problem Populating Transaction",
  TOKEN_APPROVED: "Token Approved",
  TX_SUCCESS: "Transaction Complete",
  TX_FAILED: "Transaction Failed",
};